# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.

# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true

# When configured, Gradle will run in incubating parallel mode.
org.gradle.parallel=true

# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official

# AndroidX and Jetifier
android.useAndroidX=true
android.enableJetifier=false

# Configuration Cache (Disabled for stability with KSP and Kotlin 2.0 in some environments)
org.gradle.configuration-cache=false

# KSP settings
ksp.incremental=false

# Kotlin daemon settings
# kotlin.daemon.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m -Djava.net.preferIPv4Stack=true
kotlin.compiler.execution.strategy=in-process
